name: Pathstriders
version: ${project.version}
api-version: 1.21.7
main: com.meowverdose.pathstriders.Pathstriders
author: meowphetamines
description: "§dThe Butterfly That Triggered the Storm"
commands:
  items:
    description: "Give talent item to player"
    usage: "/items <player> <talent>"
