name: Seele
version: ${project.version}
api-version: 1.19
main: org.nekoverse.seele.Seele
author: nekoverse
description: "§dThe Butterfly That Triggered the Storm"
depend:
commands:
  lookup:
  items:
  talents:
  whatis: