name: Pathstriders
version: ${project.version}
api-version: 1.21.7
main: com.meoverdose.pathsriders.Pathstriders
author: meowphetamines
description: "§dThe Butterfly That Triggered the Storm"
commands:
