name: Seele
version: ${project.version}
api-version: 1.19
main: cc.chocochip.seele.Seele
description: "The Butterfly That Triggered the Storm"
depend:
commands:
  lookup:
  items:
  talents:
  whatis: